@startuml
namespace main {
    class complexElement << (S,Aquamarine) >> {
        - attributeA string
        - attributeB string
        - attributeC int

    }
    class customElementA << (S,Aquamarine) >> {
        - attributeA string
        - attributeB string
        - attributeC int

        - setAttributeA() 
        - setAttributeB() 
        - setAttributeC() 
        - newComplexElement() complexElement

    }
    class customElementB << (S,Aquamarine) >> {
        - attributeA string
        - attributeB string
        - attributeC int

        - setAttributeA() 
        - setAttributeB() 
        - setAttributeC() 
        - newComplexElement() complexElement

    }
    class director << (S,Aquamarine) >> {
        - buildSpecification iBuilder

        - setBuilderConfiguration(specification iBuilder) 
        - buildComplexElement() complexElement

    }
    interface iBuilder  {
        - setAttributeA() 
        - setAttributeB() 
        - setAttributeC() 
        - newComplexElement() complexElement

    }
}

"main.iBuilder" <|-- "main.customElementA"
"main.iBuilder" <|-- "main.customElementB"

@enduml
